name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get Current Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag v1.0.${{ env.DATE }}
          git push origin v1.0.${{ env.DATE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ env.DATE }}
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - uses: actions/checkout@v4
#      - name: set up JDK 11
#        uses: actions/setup-java@v4
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v1
#        with:
#           files: app/build/outputs/apk/release/app-release.apk
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
